#include "game/board/main.h"
#include "game/board/effect.h"
#include "game/board/audio.h"
#include "game/board/scroll.h"
#include "game/board/model.h"
#include "game/board/masu.h"
#include "game/board/opening.h"
#include "game/board/capsule.h"
#include "game/board/branch.h"
#include "game/board/camera.h"
#include "game/board/player.h"
#include "game/board/guide.h"
#include "game/board/window.h"
#include "game/board/coin.h"
#include "game/board/roulette.h"
#include "game/board/star.h"
#include "game/board/capsule.h"
#include "game/board/status.h"
#include "game/board/com.h"

#include "game/sprite.h"
#include "game/esprite.h"
#include "game/hsfex.h"
#include "game/wipe.h"
#include "game/gamemes.h"
#include "game/mgdata.h"
#include "game/pad.h"
#include "game/main.h"

#include "game/mg/actman.h"
#include "game/mg/colman.h"
#include "game/mg/score.h"
#include "game/mg/seqman.h"
#include "game/mg/timer.h"

#include "stdio.h"
#include "stdarg.h"
#include "string.h"

